### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by ve3meo** [dwp-forge/batchedit#10]
New to Dokuwiki and PHP etc. but BatchEdit returns only 9 hits in 2 pages on the server while Notepad++ returns 32 hits in 15 pages for the same search on the same set of pages downloaded to my pc. A support person says he got 30 hits using grep on the linux server. The search term was "/postimg\.org/" for BatchEdit and, for Notepad++, "postimg.org" (simple search) or "postimg\.org" (regexp), all sans quotes.

**Comment by dwp-forge** [comment]
The plugin does not scan file system for pages like grep or Notepad++ do. Instead it uses DW page index, so it can find only those pages that DW search can find. It also takes into account DW ACL to ensure that users can modify only the pages they allowed to edit.

**Comment by ve3meo** [comment]
Thanks for the quick reply, Mykola. I will follow up with my host as to why the DW page index does not have all the pages they imported for me.

**Comment by ve3meo** [comment]
That did the trick. I found the SearchIndex Manager plugin and rebuilt the index. Now seeing many more results.
