### ISSUE TITLE
Non-existing "pencil.png" in lib/plugins/batchedit/style.css

### ISSUE THREAD

**Issue by tmo26** [dwp-forge/batchedit#15]
Dokuwiki Release 2018-04-22a "Greebo"
Batchedit Installed version:    2019-02-11

Issue: `lib/plugins/batchedit/style.css` contains the following

`background: transparent url(../../images/pencil.png) 1px 1px no-repeat;`

but `pencil.png` does not exist.

This error frequently shows up in the webservers error logs.

**Comment by dwp-forge** [comment]
It's a hobby project, not a full-time development. There are some feature requests that have been sitting there for years (literally). I finally made myself to spend some time on this, but the only timeframe I can give you is "When it's done".

The fix has been pushed to the master [already](https://github.com/dwp-forge/batchedit/commit/ac011099c9b00b316b88058984aa7cee1e681f27), so if you cannot wait for the "official" release, you can grab the latest master and have some fun with it. Let's call that "Volunteer beta-testing program" ;)

**Comment by tmo26** [comment]
I'm happy to be a beta tester :)

Installed master: works like a charm! Correct Icons are there and as far as I can see, no more findings in the error logs.
![grafik](https://user-images.githubusercontent.com/12309103/42183603-bcba81d4-7e42-11e8-8ce5-c2a826d76f95.png)

Thanks for the "Check all" button! Oh would that have only been there when I needed to click 800 checkboxes...! After having done the 800 clicks, I can only stress how important it is to review each and every finding in detail before clicking the global check all.

**Comment by dwp-forge** [comment]
Oops! Now I see it myself, no need to reproduce.

**Comment by dwp-forge** [comment]
Fixed.

**Comment by dwp-forge** [comment]
Fixed in release 2018-08-18.
