### ISSUE TITLE
exceeding php.ini 'max_input_vars'

### ISSUE THREAD

**Issue by trollkotze** [dwp-forge/batchedit#16]
When there is a huge amount of matches, this can exceed `php.ini`'s `max_input_vars` (set to 1000 [here](http://sangham.net/index.php/topic,8657.msg15138.html#msg15138) where this happened few days ago), resulting in an error.

A workaround would be to not send all the single checkbox input values in the POST request as individual array elements, but just one string variable, containing a comma-separated list of all the checked ids.

I will submit a PR for this.

**Comment by trollkotze** [comment]
PR #17 resolves this problem.

But apart from that, some sort of optional and configurable pagination could also be a very helpful feature to deal with huge result sets.

**Comment by dwp-forge** [comment]
Actually, search result pagination was one of the reasons for introducing JS to the plugin. I thought about having some AJAX-y thing going on, but so far I did not figure out how to do that in a safe way. Assuming that you have pages because you are working on some massive change, that massive change going to take you a while. What if another user comes in between and changes some page, which will result in different set of matches. Asking matches from 500 to 599 will no longer work because indexes have shifted. Also doing full wiki search on every AJAX request looks wasteful if you need only 100 matches.

If you have some ideas how to deal with this sort of issues, I would be glad to listen.

**Comment by trollkotze** [comment]
Those are some things worth thinking about.

But I don't understand enough yet to know a good answer to this. But another issue I came across yesterday was the script exceeding `php.ini`'s `max_execution_time` while doing replacement on a set of 4000+ matches.

I found that it's possible to request additional time with `setTimeLimit($seconds)`, so I added `setTimeLimit(120)` at the beginning of `applyMatches()` and `editFile()`. Not really familiar with PHP, I hope this is an acceptable solution.

I also don't know how DokuWiki's search index (or any search index, for that matter) works and how it affects the functioning of this plugin, if at all. I've learnt that the state of the search index can lag behind the actual state of page contents. The index for each file is only updated when a page is first opened in the browser, if I understand correctly, and it happened that files containing certain matches did not appear in the BatchEdit match results. But that was for files which had not ever been indexed even for the first time, because they were added manually, not through the DokuWiki interface. (After rebuilding the index with the [Search Index Plugin](https://www.dokuwiki.org/plugin:searchindex), everything was found.)

If I understand correctly, the BatchEdit plugin only uses the search index only to know which files exist at all and loop through the list of them. But it will open each file in its current state to do the actual search for matches. Is that right? (So that it would only be necessary that a file had ever been added to the search index at some point, but would not matter if its contents had been edited outside of DokuWiki, to still find all relevant matches?)

**Comment by trollkotze** [comment]
> If I understand correctly, the BatchEdit plugin only uses the search index only to know which files exist at all and loop through the list of them. But it will open each file in its current state to do the actual search for matches. Is that right? (So that it would only be necessary that a file had ever been added to the search index at some point, but would not matter if its contents had been edited outside of DokuWiki, to still find all relevant matches?)

Oh, that question [has already been cleared up](http://sangham.net/index.php/topic,8657.msg15176.html#msg15176):  :)

https://www.dokuwiki.org/plugin:batchedit#page_lookup

> So it's only about the list of files that batchEdit uses the index.

**Comment by dwp-forge** [comment]
> 4000+ matches

You are clearly abusing this thing :D

**Comment by trollkotze** [comment]
> > 4000+ matches

> You are clearly abusing this thing :D

I don't think so. ;) I think it's great to have this tool for that job.

**Comment by dwp-forge** [comment]
Fixed in release 2018-08-18.
