### ISSUE TITLE
Overly large icon in admin view

### ISSUE THREAD

**Issue by tmo26** [dwp-forge/batchedit#21]
After the update to 2018-08-18, the batchedit icon in the admin view is overly large:

![grafik](https://user-images.githubusercontent.com/12309103/45046886-c5be9b00-b077-11e8-9db1-1e033610803d.png)

Since batchedit is the only plugin showing this behaviour, there must be something wrong with this plugin.
Can you please fix it, so that the icon is shown in normal size?

**Comment by dwp-forge** [comment]
While working on the icon I was worried that it has too many small features and it will be too crowded and hard to read at 24x24 size. But **this** looks awesome! :grin: 

Seriously, though, which template do you use?

**Comment by tmo26** [comment]
It's an own template, which admittedly is quite old, but still works for every other plugin we have installed (batchedit plugin deactivated here due to the big icon):
![grafik](https://user-images.githubusercontent.com/12309103/45073157-69db2d00-b0de-11e8-801b-33e113f1e4cb.png)

I crosschecked with bootstrap3 template: Icon is shown in normal size.

**Comment by dwp-forge** [comment]
It looks like in your template you miss style for ``<span class="icon">``. On default template there is an empty spot for missing icons.

![image](https://user-images.githubusercontent.com/11460562/45075775-e5de7080-b0f0-11e8-847c-dfc8a6b49faf.png)

Try to enforce the size in admin.svg. Replace ``<svg viewBox="0 0 24 24">`` by ``<svg width="24" height="24" viewBox="0 0 24 24">``.

**Comment by tmo26** [comment]
That solved the problem, batchedit icon is now shown in normal size. Thank you! :)
Just crosschecked other plugins: They all have width/height defined.

**Comment by dwp-forge** [comment]
Yeah, they do. But IMO that's not the best way to use SVGs. Ideally, it should be up to template author to decide what the icon size should be. Apparently, not everyone shares that view.

**Comment by dwp-forge** [comment]
Fixed in [release of 2018-11-25](https://github.com/dwp-forge/batchedit/releases/tag/v.2018-11-25).
