### ISSUE TITLE
Missed checkbox

### ISSUE THREAD

**Issue by tmo26** [dwp-forge/batchedit#23]
After updating to 2018-08-18, sometimes a checkbox is not set when clicking on the "parent" checkbox":

![grafik](https://user-images.githubusercontent.com/12309103/45047517-8b55fd80-b079-11e8-9835-9b7657b71ca5.png)

First two parent checkboxes also select the child checkbox.
Third parent doesn't check the child checkbox.

Earlier I encountered this in an even more pronounced way, where every other parent checkbox didn't check the child, i.e. parent 1 - OK / 2 - NOK / 3 - OK / 4 - NOK etc.

Can you please look into this and fix it?

**Comment by dwp-forge** [comment]
Fixed in [release of 2018-11-25](https://github.com/dwp-forge/batchedit/releases/tag/v.2018-11-25).
