### ISSUE TITLE
search term missing

### ISSUE THREAD

**Issue by SimoneArnold** [dwp-forge/batchedit#29]
Although I fill out each line, after pressing preview the error "no search term" always occurs.

**Comment by dwp-forge** [comment]
Could you please add screenshots before and after pressing Preview button?

Which versions PHP, DokuWiki and BatchEdit do you use?

Are there other DW plugins installed?

Do you use any browser extensions that could interfere with JS (e.g. NoScript)?

**Comment by Dr-Yukon** [comment]
> Although I fill out each line, after pressing preview the error "no search term" always occurs.

Batchedit doesn't smash texts of nonindexed files. Did you edit your data files by external text editors even once in the history? If yes, you need:
1. to detect not indexed files through https://www.dokuwiki.org/plugin:wikistats syntax like this (for example) {{wikistats>ns = ru:sci-fi, -ru:sci-fi:commander-kitty, -ru:sci-fi:final-sunrise, -ru:sci-fi:freefall, -ru:sci-fi:sammy & type = pages}}
2. and reindex them
2.a. by https://www.dokuwiki.org/plugin:searchindex admin form (long and very long path)
2.b. or by massive replace all files to new folders (namespaces, as DW creators say).

**Comment by tmo26** [comment]
Confirmed for
Dokuwiki: Release rc-2020-06-09 "Hogfather" RC3
Batchedit: Installed version: 2019-06-02

Before preview
![grafik](https://user-images.githubusercontent.com/12309103/86953859-558e6e00-c155-11ea-9d21-e102ed9b3c4d.png)

After preview
![grafik](https://user-images.githubusercontent.com/12309103/86953885-6343f380-c155-11ea-895a-4d5e70a772f2.png)

Firefox web console output
![grafik](https://user-images.githubusercontent.com/12309103/86954116-b6b64180-c155-11ea-9c74-d7fb0e16a649.png)

**Comment by dwp-forge** [comment]
It's already fixed on master (see a44777a). I'm waiting for official Hogfather release to do final validation and release of the plugin.

**Comment by dwp-forge** [comment]
Fixed in [v.2020-07-31](https://github.com/dwp-forge/batchedit/releases/tag/v.2020-07-31).
