### ISSUE TITLE
Multi line search?

### ISSUE THREAD

**Issue by cjohnsonuk** [dwp-forge/batchedit#3]
I'm trying to update my template pages.
I have pages with the following

```
==== Description ====
==== Infrastructure ====
==== Code ====
===== Development =====
```

and some with 

```
==== Description ====
==== Infrastructure ====
==== Code ====
==== Misc Notes ====
===== Development =====
```

I want to insert a "Misc Notes" title after the "Code" title _only_ if its not there already.

I've tried a reg exp of
    /==== Code ====\s*(?!==== Misc notes ====)/  
With a replacement of 
    ==== Code ==== \\ ==== Misc notes ==== 

but it appears that I'm not matching any new lines so I end up with two sections called Misc notes where it already appears
and the \\ in the replace might put a new line in with wiki syntax but I'd prefer to use real line breaks (I've tried \r\n, \n, \r  with no luck).

Any help appreciated...

**Comment by dwp-forge** [comment]
You could try to take the bundle from [master head](https://github.com/dwp-forge/batchedit/archive/master.zip). That does it for me:
- **Expression:** `/==== Code ====\n(?!==== Misc Notes ====)/`
- **Replacement:** `==== Code ====\n==== Misc Notes ====\n`

There was a patch (ba862f97) specifically dedicated for support of `\n` in the replacement but I never got around to make a proper release out of it. And some Good Samaritan already "fixed" the download link on the plugin page from the official release to whatever the master is. You are not first.
