### ISSUE TITLE
Limit up

### ISSUE THREAD

**Issue by Dr-Yukon** [dwp-forge/batchedit#32]
How can I change the limit? https://github.com/dwp-forge/batchedit/blob/master/config.php#L25 don't help me, conf/default.php
```
+ $conf['searchmax'] = 1000;
+ $conf['searchlimit'] = 1;
```
don't help me too

**Comment by dwp-forge** [comment]
Are we talking about this thing?

![image](https://user-images.githubusercontent.com/11460562/73491690-d7fd4f80-43b7-11ea-91dc-663c7f3f1610.png)

**Comment by Dr-Yukon** [comment]
≺(°o°)≻ wow
