### ISSUE TITLE
Search pattern limiter

### ISSUE THREAD

**Issue by Dr-Yukon** [dwp-forge/batchedit#34]
I need a limiter for search patterns [screenshot](http://screenshot.ru/ca9eca0af74f153989b900951844e83c.png) for replacing `== Freefall h0061 ==` to `== Freefall 0611 - 0620`. But if I use `== Freefall h0(\d\d)1 == / == Freefall $111 - $120 ==` and got `== Freefall 1 - 0 ==`. Now I forced to use ᆺ as limiter in `== Freefall $1ᆺ11 - $1ᆺ20 ==`

I need to use incorporated $n with any auto replacing delimiter symbol

**Comment by Dr-Yukon** [comment]
oh. `$0111 - $0120` works fine ._.

**Comment by dwp-forge** [comment]
[In this case the solution is to use ${1}1.](https://www.php.net/manual/en/function.preg-replace.php)

**Comment by Dr-Yukon** [comment]
Hmm, I tried first {$1}
