### ISSUE TITLE
"Check all"?

### ISSUE THREAD

**Issue by per-hed** [dwp-forge/batchedit#4]
I'd like the option to be able to select all checkboxes after a search. 

This could of course be dangerous, but once all search hits have been thoroughly checked it can be a pain to manually click every single checkbox (some of my operations have had hundreds!) in order to execute the replace action.

Would much rather have an additional "Are you sure?" dialog... 

Thanks in advance!

**Comment by fthommen** [comment]
I'd support this very much.  batchedit just saved my day, but having a single "select all" instead of selecting 230 entries individually would have made it even easier :-))

**Comment by trailjeep** [comment]
I too would like this feature.

In  the meantime I've used this in the javascript console:
`javascript:[].forEach.call(document.querySelectorAll('input[type="checkbox"]'),function(el){el.checked=true});
`
Of course, it also checks Summary: Minor changes.

Adding here as a note to self for future reference.

**Comment by joergdd** [comment]
That would be wonderful.

**Comment by dwp-forge** [comment]
Implemented in release 2018-08-18.
