### ISSUE TITLE
UI page not scaling to fit

### ISSUE THREAD

**Issue by auximenes** [dwp-forge/batchedit#41]
The right side of the admin page is not showing as the table in "be-mainform" is taking up the full width available. This is with the default template in Hogfather. Thanks.

![Screenshot](https://user-images.githubusercontent.com/81241892/112152374-22541800-8bda-11eb-99eb-fa761ce86d19.png)

**Comment by dwp-forge** [comment]
Did you try to wipe DW cache?

Which browser do you use?

**Comment by auximenes** [comment]
It's a Safari issue: works fine in Chrome, but I didn't think to check that. Sorry. Persists in Safari 11 & 14, despite emptying the cache. I'll use Chrome for admin tasks…

**Comment by dwp-forge** [comment]
Unfortunately, I don't have access to Safari. So unless someone else will provide a fix, Chrome would be your way out of this. This table layout depends on CSS Flexbox, and it seems that Safari [is supposed to support that](https://caniuse.com/flexbox). I guess, Apple should consider joining [these guys](https://www.engadget.com/google-microsoft-browser-compatibility-issues-104040745.html) ;)
