### ISSUE TITLE
Using namespace templates pattern

### ISSUE THREAD

**Issue by chtiland** [dwp-forge/batchedit#44]
Hello !

I also use searchpattern plugin, and today I use a template where I want to add this :

`~~SEARCHPATTERN;'@PAGE@'??-??~~`

But I already created more than 350 pages with this template. So I want to add this to these pages with Batchedit, but pattern `@PAGE@` is kept as it, and it would be nice if this one was replaced with page name.

Is there a way to use [namespaces replacement patterns](https://www.dokuwiki.org/namespace_templates#replacement_patterns) in _Replace with_ field ?
If not, I think it would be a good feature to add 😃 

Thanks for this great plugin really useful !
Fabrice

**Comment by dwp-forge** [comment]
It is not possible at the moment.

**Comment by dwp-forge** [comment]
I think this is a nice idea, so I added [an advanced option to do such a replacement](https://github.com/dwp-forge/batchedit/commit/c59ed5bd671d30ea0bea565306417d427f66fd51). This is **not an official release** yet, I'm still waiting for localization updates. But if you want to try it out, you can install [this version](https://github.com/dwp-forge/batchedit/archive/c59ed5bd671d30ea0bea565306417d427f66fd51.zip).

**Comment by chtiland** [comment]
Hello !

I've just tried it, works fine !!! Thanks 👍🏼 

One more minor bug yet, main search box's height is not enough to display the new option when showing options.
I think it's due to french language : 

![image](https://user-images.githubusercontent.com/298526/152681582-fef8ddb2-6436-4b16-b626-c644d6c66100.png)

I used Stylus (Firefox extension)  to force height to 300px to be able to use this option.

```css
/* BatchEdit */
#batchedit #be-mainform {
  height: 300px;
}
```

**Comment by chtiland** [comment]
Hello,

As I was there, I made french translation and changed `$lang['dim_extoptions'] = '28em'; ` to `$lang['dim_extoptions'] = '36em';`, thus no need to change CSS :
![image](https://user-images.githubusercontent.com/298526/152683239-fe8b369d-2e6f-4fe3-81c6-563c1da04e9a.png)

Thanks
Fabrice

**Comment by dwp-forge** [comment]
Releases as [v.2022-02-19](https://github.com/dwp-forge/batchedit/releases/tag/v.2022-02-19). You may need to update your clone since there was a forced update on the master branch.
