### ISSUE TITLE
Replace not performed when search has lookahead assertion

### ISSUE THREAD

**Issue by suedunham** [dwp-forge/batchedit#50]
When my search pattern includes a negative lookahead assertion, like `(?! in)` looking for a space and the word "in" beyond the end of the pattern, the plugin finds the matches and previews the changes correctly. However, pressing the Apply button does nothing.

If I remove the pattern or change it to a plain group, the replacement works fine.

I have not yet tried positive lookahead assertions, like `(?= in)` or any lookbehind assertions.

**Comment by dwp-forge** [comment]
As for me, it seems to work:

![image](https://github.com/dwp-forge/batchedit/assets/11460562/709a3932-9c65-4210-b874-7b8354386e84)

Could you please provide more details about your test case?
