### ISSUE TITLE
reg exp fails, but then works later

### ISSUE THREAD

**Issue by cjohnsonuk** [dwp-forge/batchedit#6]
I'm doing 2 searches in all pages (leaving the namespace blank)for the pattern
/png\?(\d+)\s+/
or 
/png\?direct\&(\d+)\s+/

which will find all images that have a width followed by a space 
I'm replacing this with 

png?$1&nolink 
or
png?direct&$1&nolink 

so that the image keeps its width but is not set as a link.  I'm doing this to remove internal wiki hyper links from pages exported as PDF using DW2PDF

I'll run the preview and it will come back with no results but when I check the pages again for links then these (examples) are still found.

{{ :generic:authority:topics:2016-11-07_16_19_45-documents_selection_screen.png?direct&600 |}}
then on the next screen
{{ :generic:authority:topics:2016-11-07_16_24_10-uploading_doc_record.png?direct&600 |}}

I've tried swapping (\d+) for the real number found, that makes no difference
I've tried adding : to the namespace to force searching from root

I've tested the reg ex in http://www.phpliveregex.com/ and they should work so I think its a file search issue rather than a matching issue.

What am I doing wrong? 
(latest dokuwiki  2017-02-19e "Frusterick Manners" and batch edit  )

**Comment by dwp-forge** [comment]
Missing backslash before question mark.

`/png\?(\d+)\s+/
`

**Comment by cjohnsonuk** [comment]
Tried that and it didn't work.  Still not sure what caused it but coded my way around it by adding custom code to the DW2PDF plugin to strip matching html links before output so i don't need to no link text in the real wiki.
