### ISSUE TITLE
Feature request : Option to only show the latest version of each page in the matches

### ISSUE THREAD

**Issue by cjohnsonuk** [dwp-forge/batchedit#7]
Can we have a tick box that says only show latest version of each matching page so that if I have 40 versions of a page that match and I only need to change the most recent one then I can do just that without having to look down the list of 40 pages and find the most recent?

**Comment by joergdd** [comment]
That would be wonderful.

**Comment by dwp-forge** [comment]
I'm not sure what you mean by page version, is it about page revisions stored in attic? The plugin gets list of pages from DW page index. AFAIK, there is no revision information in the index and even if there would, the plugin does not attempt to read it.

Could you please provide a screenshot with multiple page versions being matched?

**Comment by dwp-forge** [comment]
Abandoned due to unclear issue description.
